version: "3"

volumes:
  ldproxy_data:

services:

  ldproxy:
    
    image: iide/ldproxy:latest

    container_name: ldproxy

#    expose:
#      - "80"

    ports:
     - "80:7080"

    volumes:
      - ldproxy_data:/ldproxy/data
    
    labels:
      - "traefik.enable=true"
      # local http router
      - "traefik.http.routers.ldproxy_lhttp.rule=Host(`local.map5.nl`) || Host(`localhost`) && PathPrefix(`/ldproxy`)"
      - "traefik.http.routers.ldproxy_lhttp.entrypoints=http"
      - "traefik.http.routers.ldproxy_lhttp.middlewares=secure-headers@file"
      # https router
      - "traefik.http.routers.ldproxy_https.rule=Host(`oapi.map5.nl`) && PathPrefix(`/ldproxy`)"
      - "traefik.http.routers.ldproxy_https.entrypoints=https"
      - "traefik.http.routers.ldproxy_https.tls=true"
      - "traefik.http.routers.ldproxy_https.tls.certresolver=le"
      - "traefik.http.routers.ldproxy_https.tls.options=my_default@file"
      - "traefik.http.routers.ldproxy_https.middlewares=secure-headers@file"

      - "traefik.frontend.priority=100"
      - "traefik.docker.network=service-network"

networks:
  default:
    external:
      name: service-network
