version: "3.3"

services:

  ldproxy:
    # Seems 'latest' is another version
    image: ${DOCKER_IMAGE}

    container_name: ${SERVICE_NAME}

    expose:
      - "7080"

#    ports:
#      - "7080:7080"
    
    volumes:
      - ./data:/ldproxy/data
    
    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # This will replace any /ldproxy/* with /rest/services/* when calling the ldproxy container
      - "traefik.http.middlewares.${SERVICE_NAME}_replace_restservices_path.replacepathregex.regex=${SERVICE_PATH}(.*)"
      - "traefik.http.middlewares.${SERVICE_NAME}_replace_restservices_path.replacepathregex.replacement=/rest/services$$1"

      - "traefik.http.middlewares.${SERVICE_NAME}_replace_manager_path.replacepathregex.regex=${SERVICE_PATH_MANAGER}(.*)"
      - "traefik.http.middlewares.${SERVICE_NAME}_replace_manager_path.replacepathregex.replacement=/manager$$1"

      # SSL/https router
      - "traefik.http.routers.${SERVICE_NAME}_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.options=my_default@file"
      - "traefik.http.routers.${SERVICE_NAME}_https.middlewares=secure-headers@file,${SERVICE_NAME}_replace_restservices_path"

      # local http router - REST services
      - "traefik.http.routers.${SERVICE_NAME}_http.rule=Host(`localhost`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_http.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}_http.middlewares=${SERVICE_NAME}_replace_restservices_path"

      # local http router - for ldproxy Manager
      - "traefik.http.routers.${SERVICE_NAME}_manager_http.rule=Host(`localhost`) && PathPrefix(`${SERVICE_PATH_MANAGER}`)"
      - "traefik.http.routers.${SERVICE_NAME}_manager_http.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}_manager_http.middlewares=${SERVICE_NAME}_replace_manager_path"

networks:
  default:
    external:
      name: service-network
