version: "3.3"

services:

  ldproxy:
    # Seems 'latest' is another version
    image: iide/ldproxy:master

    container_name: ldproxy

    expose:
      - "7080"

#    ports:
#      - "7080:7080"
    
    volumes:
      - ./data:/ldproxy/data
    
    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # This will replace any /ldproxy/* with /rest/services/* when calling the ldproxy container
      - "traefik.http.middlewares.ldproxy-replace-restservices-path.replacepathregex.regex=/ldproxy(.*)"
      - "traefik.http.middlewares.ldproxy-replace-restservices-path.replacepathregex.replacement=/rest/services$$1"

      - "traefik.http.middlewares.ldproxy-replace-manager-path.replacepathregex.regex=/manager_ldproxy(.*)"
      - "traefik.http.middlewares.ldproxy-replace-manager-path.replacepathregex.replacement=/manager$$1"

      # SSL/https router
      - "traefik.http.routers.ldproxy_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`/ldproxy`)"
      - "traefik.http.routers.ldproxy_https.entrypoints=https"
      - "traefik.http.routers.ldproxy_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.ldproxy_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.ldproxy_https.tls.options=my_default@file"
      - "traefik.http.routers.ldproxy_https.middlewares=secure-headers@file,ldproxy-replace-restservices-path"

      # local http router - REST services
      - "traefik.http.routers.ldproxy_http.rule=Host(`localhost`) && PathPrefix(`/ldproxy`)"
      - "traefik.http.routers.ldproxy_http.entrypoints=http"
      - "traefik.http.routers.ldproxy_http.middlewares=ldproxy-replace-restservices-path"

      # local http router - for ldproxy Manager
      - "traefik.http.routers.ldproxy_manager_http.rule=Host(`localhost`) && PathPrefix(`/manager_ldproxy`)"
      - "traefik.http.routers.ldproxy_manager_http.entrypoints=http"
      - "traefik.http.routers.ldproxy_manager_http.middlewares=ldproxy-replace-manager-path"

networks:
  default:
    external:
      name: service-network
