version: '3.3'

# See env.sh and ../env.sh for env vars
services:

  qgis:
    
    image: ${DOCKER_IMAGE}

    container_name: ${SERVICE_NAME}

    expose:
      - "80"

#    ports:
#     - "5000:80"

    environment:
      - QGIS_SERVER_LOG_LEVEL:0
      #- PGSERVICEFILE:If you want to change the default of /etc/qgisserver/pg_service.conf
      - QGIS_PROJECT_FILE:/etc/qgisserver/project.qgs
      #- QGIS_SERVER_IGNORE_BAD_LAYERS:true
      #- MAX_REQUESTS_PER_PROCESS:The number of requests a QGIS server will serve before being restarted by apache
      #- QGIS_CATCH_SEGV:1

    volumes:
      # Map data and config into  container
      - ./data:/etc/qgisserver

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # SSL/https router
      - "traefik.http.routers.${SERVICE_NAME}_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.options=my_default@file"
      - "traefik.http.routers.${SERVICE_NAME}_https.middlewares=secure-headers@file"

      # local http router
      - "traefik.http.routers.${SERVICE_NAME}_http.rule=Host(`localhost`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
