version: '3.3'

services:

  home:
    
    build: ./

    container_name: home

    expose:
      - "8000"

#    ports:
#     - "5000:8000"

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # SSL/https router
      - "traefik.http.routers.home_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`)"
      - "traefik.http.routers.home_https.entrypoints=https"
      - "traefik.http.routers.home_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.home_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.home_https.tls.options=my_default@file"
      - "traefik.http.routers.home_https.middlewares=secure-headers@file"

      # local http router
      - "traefik.http.routers.home_http.rule=Host(`localhost`)"
      - "traefik.http.routers.home_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
