# EXAMPLE FILE - your encrypted vars.yml should cotnain the following vars
---
my_ssh_pubkey_file: ~/.ssh/id_rsa.pub
my_email: me@ergens.nl
my_admin_user: adminuser
my_admin_home: "/home/{{ my_admin_user }}"
my_git_home: "{{ my_admin_home }}/git"
my_github_repo: https://github.com/Geonovum/ogc-api-testbed.git
var_dir: /var/ogcapi
logs_dir: "{{ var_dir }}/log"
services_home: "{{ my_git_home }}/services"
platform_home: "{{ my_git_home }}/platform"
pip_install_packages:
  - name: docker
timezone: Europe/Amsterdam
ufw_open_ports: ['22', '80', '443', ...]
postgis_env:
  PG_DB: the_db_name
  PG_USER: the_db_user
  PG_PASSWORD: the_db_password
  PGADMIN_EMAIL: gis@gis.gis
  PGADMIN_PASSWORD: the_pgadmin_password
geohealthcheck_env:
  POSTGRES_HOST: ghc_db
  POSTGRES_PORT: 5432
  PG_GHC_DB: the_info
  PG_GHC_USER: the_info
  PG_GHC_PASSWORD: the_info
  GHC_ADMIN_EMAIL: the_info@the_info.com
  GHC_SMTP_SERVER: the_info.com
  GHC_SMTP_PORT: the_info
  GHC_SMTP_TLS: the_info
  GHC_SMTP_SSL: the_info
  GHC_SMTP_USERNAME: the_info
  GHC_SMTP_PASSWORD: the_info
  SQLALCHEMY_DATABASE_URI: postgresql://the_info:the_info@the_info:5432/the_info
  ADMIN_NAME: the_info
  ADMIN_PWD: the_info
  ADMIN_EMAIL: the_info@the_info.nl
  GHC_NOTIFICATIONS_EMAIL: the_info@the_info.com
