# EXAMPLE FILE - your encrypted vars.yml should cotnain the following vars
---
my_ssh_pubkey_file: ~/.ssh/id_rsa.pub
my_email: me@ergens.nl
my_admin_user: adminuser
my_admin_home: "/home/{{ my_admin_user }}"
my_git_home: "{{ my_admin_home }}/git"
my_github_repo: https://github.com/Geonovum/ogc-api-testbed.git
var_dir: /var/ogcapi
logs_dir: "{{ var_dir }}/log"
services_home: "{{ my_git_home }}/services"
platform_home: "{{ my_git_home }}/platform"
pip_install_packages:
  - name: docker
timezone: Europe/Amsterdam
ufw_open_ports: ['22', '80', '443', ...]
postgis_env:
  PG_DB: the_db_name
  PG_USER: the_db_user
  PG_PASSWORD: the_db_password
  PGADMIN_EMAIL: gis@gis.gis
  PGADMIN_PASSWORD: the_pgadmin_password
