version: '3.3'

services:

  pycsw:
    
    image: geopython/pycsw:latest

    container_name: pycsw

    expose:
      - "8000"

#    ports:
#     - "5000:80"

    environment:
      - SCRIPT_NAME=/pycsw/csw.py

    volumes:
      # Map data and config into  container
      - ./data:/var/lib/pycsw
      - ./pycsw.cfg:/etc/pycsw/pycsw.cfg

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"
      - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/pycsw"

      # SSL/https router
      - "traefik.http.routers.pycsw_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`/pycsw`)"
      - "traefik.http.routers.pycsw_https.entrypoints=https"
      - "traefik.http.routers.pycsw_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.pycsw_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.pycsw_https.tls.options=my_default@file"
      - "traefik.http.routers.pycsw_https.middlewares=secure-headers@file"

      # local http router
      - "traefik.http.routers.pycsw_http.rule=Host(`localhost`) && PathPrefix(`/pycsw`)"
      - "traefik.http.routers.pycsw_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
