version: '3.3'

# See env.sh and ../env.sh for env vars
services:

  pygeoapi:
    
    image: ${DOCKER_IMAGE}

    container_name: ${SERVICE_NAME}

    expose:
      - "80"

    #    ports:
    #     - "5000:80"

    environment:
      # Specific to Flask apps
      - SCRIPT_NAME=${SERVICE_PATH}

    volumes:
      # Map data and config into pygeoapi container
      - ./local.config.yml:/pygeoapi/local.config.yml
      - ./data:/pygeoapi/data

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # Define SSL/https router
      - "traefik.http.routers.${SERVICE_NAME}_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.options=my_default@file"
      - "traefik.http.routers.${SERVICE_NAME}_https.middlewares=secure-headers@file"

      # Define local http router
      - "traefik.http.routers.${SERVICE_NAME}_http.rule=Host(`localhost`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
