server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://apitestbed.geonovum.nl/pygeoapi
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:3857/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://pdok.nl">PDOK Kadaster</a>'
#        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
#        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/master.log

metadata:
    identification:
        title: GeoNovum OGC API testbed
        description: An implementation showing use of pygeoapi as INSPICE download service
        keywords:
            - geospatial
            - data
            - INSPIRE
            - Download service
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/3.0/
        url: https://www.nationaalgeoregister.nl/geonetwork/srv/metadata/45eaae76-874a-4fe1-88f4-820517e3de73
    license:
        name: CC-BY 3.0 license
        url: http://creativecommons.org/licenses/by/3.0/nl/
    provider:
        name: Rijksdienst Cultureel Erfgoed
        url: https://www.cultureelerfgoed.nl
    contact:
        name: Rijksdienst voor het Cultureel Erfgoed - InfoDesk
        position: Helpdesk
        address: Postbus 1600 
        city: Amersfoort
        stateorprovince: Utrecht
        postalcode: 3800 BP
        country: The Netherlands
        phone: +31 633 4217456
        fax: +31 633 4217799
        email: info@cultureelerfgoed.nl
        url: https://www.cultureelerfgoed.nl
        role: pointOfContact

resources:
    ProtectedSites:
        type: collection
        title: Werelderfgoed
        description: In deze dataset zijn de begrenzingen opgenomen van het Nederlandse cultureel erfgoed dat vanwege haar uitzonderlijke universele waarde door het Werelderfgoed comite van UNESCO is geplaatst op de Werelderfgoedlijst. De gegevens in de dataset zijn conform INSPIRE geharmoniseerd.
        keywords:
            - Werelderfgoed
            - Protected sites
        crs:
            - EPSG:4258
        links:
            - type: text/html
              rel: describedby
              title: Metadata as HTML
              href: https://www.nationaalgeoregister.nl/geonetwork/srv/metadata/45eaae76-874a-4fe1-88f4-820517e3de73
              hreflang: nl
            - type: application/xml
              rel: describedby
              title: Metadata as iso19139 xml
              href: https://www.nationaalgeoregister.nl/geonetwork/srv/metadata/45eaae76-874a-4fe1-88f4-820517e3de73/formatters/xml
              hreflang: nl
            - type: text/html
              rel: tag
              title: Referentie naar het concept beschermde gebieden (inspire registry)
              href: http://inspire.ec.europa.eu/featureconcept/ProtectedSite
              hreflang: nl
            - type: application/gml+xml
              rel: enclosure
              title: Download volledige dataset Werelderfgoed als GML
              href: https://service.pdok.nl/rce/ps-ch/wfs/v1_0?request=GetFeature&service=WFS&version=1.1.0&typeName=ps-ch:rce_inspire_polygons&outputFormat=text%2Fxml%3B%20subtype%3Dgml%2F3.1.1
              hreflang: nl
        extents:
            spatial:
                bbox: [4.40, 51.76, 5.80, 52.85]
                crs: http://www.opengis.net/def/crs/OGC/1.3/EPSG:4258
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: GPKG
                  source: data/rce.gpkg
                  source_srs: EPSG:4258
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True

                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 64
                      # GDAL_HTTP_PROXY: (optional proxy)
                      # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                      CPL_DEBUG: NO

              id_field: gml_id
              title_field: text
              layer: rce

    dutch_windmills:
        type: collection
        title: Windmills within The Netherlands
        description: Locations of windmills within the Netherlands from Rijksdienst voor het Cultureel Erfgoed (RCE) INSPIRE WFS. Uses GeoServer WFS v2 backend via OGRProvider.
        keywords:
            - Netherlands
            - INSPIRE
            - Windmills
            - Heritage
            - Holland
            - RD
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/291afe4b-4f4b-497c-8026-fb437c4e9c7e
              hreflang: nl-NL
        extents:
            spatial:
                bbox: [3.37,50.75,7.21,53.47]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: WFS
                  source: WFS:https://services.rce.geovoorziening.nl/landschapsatlas/wfs?
                  source_srs: EPSG:28992
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True

                  source_options:
  #                    OGR_WFS_VERSION: 1.1.0
                      OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO

                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 64
                      # GDAL_HTTP_PROXY: (optional proxy)
                      # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                      CPL_DEBUG: NO

              id_field: gml_id
              layer: landschapsatlas:Molens
