version: "3.3"

services:

  goaf:
    image: ${DOCKER_IMAGE}
 
    container_name: ${SERVICE_NAME}

    expose:
      - "8080"

#    ports:
#      - "7080:7080"
    
    volumes:
      - ./data:/data
    
    environment:
      - PATH_GPKG=/data/data.gpkg
      - PROVIDER=gpkg
      - ENDPOINT=${SERVICE_PATH}

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # This will replace any ${SERVICE_PATH}/* with /rest/services/* when calling the goaf container
#      - "traefik.http.middlewares.goaf-replace-restservices-path.replacepathregex.regex=${SERVICE_PATH}(.*)"
#      - "traefik.http.middlewares.goaf-replace-restservices-path.replacepathregex.replacement=/rest/services$$1"

      # SSL/https router
      - "traefik.http.routers.${SERVICE_NAME}_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.options=my_default@file"
      - "traefik.http.routers.${SERVICE_NAME}_https.middlewares=secure-headers@file"

      # local http router - REST services
      - "traefik.http.routers.${SERVICE_NAME}_http.rule=Host(`localhost`) && PathPrefix(`${SERVICE_PATH}`)"
      - "traefik.http.routers.${SERVICE_NAME}_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
